CREATE TABLE Contacts (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES Users ON DELETE CASCADE,
    contact_name VARCHAR(32) NOT NULL,
    phone VARCHAR(15) NOT NULL CONSTRAINT phone_chk CHECK (phone SIMILAR TO '\+?[0-9]+')
);
